import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/ui/navbar";
import { SessionProvider } from "@/components/contexts/session-provider";
import { auth } from "@/lib/auth";
import { getUser } from "@/lib/prisma-crud";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    let email = "";
    let colorScheme = "";
    if (!!session?.user?.email) {
        email = session.user.email;
    }

    const dbUser = await getUser({ email });

    if (dbUser && typeof dbUser === "object" && "colorScheme" in dbUser) {
        colorScheme = dbUser.colorScheme as string;
    }

    return (
        <html lang='en' className={`${colorScheme}` || "theme-purple"}>
            <body className={`${inter.className}`}>
                <SessionProvider session={session}>
                    <ThemeProvider
                        attribute='class'
                        defaultTheme='system'
                        enableSystem
                        disableTransitionOnChange
                    >
                        <Navbar />
                        {children}
                    </ThemeProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
